---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 15925.
--- DateTime: 2024/2/26 14:25
---

-- 1. 参数列表
-- 1.1.优惠券id
local voucherId = ARGV[1]
-- 1.2.用户id
local userId = ARGV[2]
-- 1.3 订单id
local orderId = ARGV[3]

-- 2.数据key
-- 2.1.库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2.订单key
local orderKey = 'seckill:order:' .. voucherId

-- 3.脚本业务
-- 3.1.判断库存是否充足
if(tonumber(redis.call('get', stockKey)) <= 0) then
    -- 3.2 库存不足，返回1
    return 1
end
-- 3.3 判断用户是否下过单
if(redis.call('sismember', orderKey, userId) == 1) then
    -- 3.4 存在，说明用户重复下单
    return 2
end

-- 3.5 扣库存
redis.call('incrby', stockKey, -1)
-- 3.6 下单(保存用户) sadd orderKey userId
redis.call('sadd', orderKey, userId)
-- 3.7 向stream.orders中添加消息 XADD stream.orders * k1 v1 k2 v2 ...
redis.call('xadd', 'stream.orders', '*', 'voucherId', voucherId, 'userId', userId, 'id', orderId)
return 0